### ISSUE TITLE
my bot dies

### ISSUE THREAD

**Issue by SlimeyManuel213** [TTtie/TTtie-Bot#3]
pls wtf is happening halp my bot and yours is crashing

**Comment by TTtie** [comment]
w8 gonna inspect bug

**Comment by SlimeyManuel213** [comment]
omfg its broken in my server wont even speak in voice chat and does not press enterrr

**Comment by TTtie** [comment]
>won't even speak in voice chat.
how?
>doesn't press enter
ah, to make a new line, place `\n` into the message

**Comment by SlimeyManuel213** [comment]
i have 2 antiviruses does that affect stuff?

**Comment by TTtie** [comment]
It might, as it lowers the performance and also, the antiviruses will start a "battle"

**Comment by SlimeyManuel213** [comment]
malwarebootes and avast does that do anything?

**Comment by TTtie** [comment]
malwarebytes is an antimalware which is launched on-demand if free
and i use avast and nothing

**Comment by SlimeyManuel213** [comment]
well i have wooondows 10 aswell

**Comment by TTtie** [comment]
Describe the problem.

**Comment by TTtie** [comment]
Screenshot the command prompt/terminal window.
